### ISSUE TITLE
Suggestion: Implement support for 3M bayonet-style filters, e.g. 6003 OV/AG, or similar

### ISSUE THREAD

**Issue by VIXIVIXIV** [nevermore3d/Nevermore_Micro#10]
Performance-wise, this should be the best option; these filters are NIOSH approved (granted, only for use with a compatible facepiece) for keeping organic vapor exposure under exposure limits (while the paper documentation is not too clear on what "organic vapors" encompasses, 3M's service life calculator ([https://sls.3m.com/](https://sls.3m.com/)) provides a wide range of potential contaminants to check filter compatibility and lifespan against).

Arguments can be had about the economy of the filters, but the calculator suggests reasonable lifespan before reaching its built-in exposure limits, which are very conservative (e.g. the calculator will report time to reach breakthrough of 10% of the exposure concentration or half of the OSHA exposure limit, whichever is lower, at which point the cartridge will likely still outperform brand-new loose carbon). The cost of a pair of cartridges is about $14, if bought in bulk that drops to about $10 a pair, and a single cartridge is likely sufficient for this application (the respirators use 2 cartridges in parallel to reduce the restriction on breathing and improve comfort, for the Nevermore the added restriction of a single cartridge can be overcome with more powerful fans). The cartridges would also be easier and faster to replace and have a wide range of options available for different VOC contaminant profiles or particle filtration performance.

If that still proves too expensive, users also have the option of purchasing knockoff/off-brand cartridges, such as [these](https://www.amazon.com/Trudsafe-Organic-Replacement-Cartridge-Respirator/dp/B07Z7MFG22l).

**Comment by 0ndsk4** [comment]
There are several 3D printer adaptions for 3M breather cartridges out there. While cost is one part, a respirator if made for high pressure (breath is 50-100x stronger than a fan)  / low volume (breath is 0.22cfm). 

If we run 2cfm through a filter made for 0.22cfm it would likely deplete 10x faster too. All in all, I’m
 It sold on the idea.
