### ISSUE TITLE
Artefacts in Nevermore Area

### ISSUE THREAD

**Issue by DietZnX** [nevermore3d/Nevermore_Micro#11]
Hello , I print the V2 Duo_Catridge and found some artefacts in the front area on my print . I see that it comes from the stl . Enclosed some pictures . !

I love the Nevermore ! Thank you for that :) 

![image](https://user-images.githubusercontent.com/101671149/172349603-207a564b-0e60-4095-bb48-a50c770bc6a4.jpeg)

![image](https://user-images.githubusercontent.com/101671149/172350017-e3884aa8-f076-4d0a-9df7-63f170be1140.jpeg)

**Comment by 0ndsk4** [comment]
Strange, I'll investigate that. Thanks.

**Comment by MandicReally** [comment]
Came to point out this same thing. Had hoped to just re-export the STL as it looks like a bad export to me, but the CAD files don't seem to include either cartridge housing.

**Comment by bucknova** [comment]
Verified artifacts on STL file. 
Will look into clearing up.

**Comment by bucknova** [comment]
Inspected F3D files. Artifacts are not on original models. 
I will export and re-upload the STL files.

**Comment by bucknova** [comment]
Cause of artifacts determined to be extruded text and fillets. 

Reworked the texts, and filleted to a smaller degree. New design has a cleaner topography and tessellates better in slicing software. 

I will update all remaining pieces. After the parts have been updated for support material, they will be published.

**Comment by Neolker** [comment]
Can I just ask for this part, I've been waiting for it for quite a while, or will there be major changes on the other parts as well so I have to wait anyway? Thanks in advance.

**Comment by bucknova** [comment]
Files have been updated. 
I will have them pushed to the GitHub shortly. 

Issue has been resolved.
