### ISSUE TITLE
DUO XL 3mf slices without bottom

### ISSUE THREAD

**Issue by 00Roc** [nevermore3d/Nevermore_Micro#13]
Cura slicer will slice/print the latest Duo XL 3mf without a bottom.  

SuperSlicer acknowledges different parts of the file and asks if they are part of the same object and resolves whatever issue Cura cannot.

So - the 3mf file cannot be sliced w/ CURA, but can function w/ SuperSlicer.

**Comment by 0ndsk4** [comment]
Ok, I'll try to upload it as a stl as the positioning data of the 3mf causes some issues.

It will slice fine with cura, but you first have to select both bodies, right click and group them, then drag them above the build plate.
