### ISSUE TITLE
Update DUO_plenum.f3d with front edge chamfer

### ISSUE THREAD

**Issue by ChainsDD** [nevermore3d/Nevermore_Micro#15]
The CAD file is missing the chamfer around the edge of the mating surface. This makes it difficult to make a modded plenum that mates with the cartridge properly.

**Comment by bucknova** [comment]
Verified missing chamfer on v2 of the DUO_Plenum file. 
Added chamfer to plenum and lid. 
Update will be published.

Issue resolved.
