### ISSUE TITLE
VOC Monitoring Question

### ISSUE THREAD

**Issue by MammothTanker114211** [nevermore3d/Nevermore_Micro#18]
Hello, I am looking to gain more information on VOC monitoring. The Nevermore Max readme contains info on VOC monitoring, and references research from Dr. Dave. Does the nevermore team have a link to his research, or know of any VOC sensors that are well suited for FDM printing. Thank you
 "Ever wondered when  its time to swap carbon? Well, on the max you could add VOC sensors to both intake
and exhaust and measure how well the filter is doing its job! Thanks to **Dr Dave**
there are even data on which sensors reliably detect the aromatic VOCs we strive
to catch (a lot of sensors hardly detect extrusion VOCs at all as they are intended
for other applications)"

**Comment by 0ndsk4** [comment]
Currently, VOC sensors are quite inferior to our own noses. 

As of now, we know SPG30/40 VOC sensors does reliably detect ABS extrusion, BME680/688 does not, and ENS160 is somewhere inbetween. But the step from detecting extrusion to having a useful implementation is huge, there are simply a huge amount of variables (the largest being how much residue is on your panels already when installing a filter...). And even when simply using the delta of intake/exhaust, voc figures change with air speed, and during long prints (24h+) sensor readings regress towards the mean no matter the pollution. There's a  lot needed software side for a reliable solution, so we're quite far away as of right now.
