### ISSUE TITLE
Will Noctua fans fit?

### ISSUE THREAD

**Issue by cdmichaelb** [nevermore3d/Nevermore_Micro#20]
Noctua comes in 5v and 24v variants and tend to be very quiet.

**Comment by 0ndsk4** [comment]
Carbon filters have high pressure drop when thick enough to catch VOCs. That means high static pressure, which means blower type fans or server fans. 
Noctua fans are axial with very low static pressure. They will not push enough air through thick filters (for reference, axial noctuas are between 0.5-4 mmH2O or pressure compared to blowers that has 15-25 mmH2O. 

afaik, noctua has neither high-rpm server fans or blowers, and wouldn’t be very suitable. Open for suggestions though!
