### ISSUE TITLE
V5 Slide-in Magnet mod interference with lip on lid

### ISSUE THREAD

**Issue by Flipsoul** [nevermore3d/Nevermore_Micro#23]
Slide in magnet mod adds slots for magnets to roll-in on at front of plenum. These interfere ~1.5 mm with the lip on the plenum lid. easy to clip the added feature back. But it seems it could be reduced without loss to printability or function

**Comment by mechatroniks-git** [comment]
I'm looking at the CAD model, getting ready to print this. I'm not seeing any interference. Can you confirm where you are seeing it?

![image](https://user-images.githubusercontent.com/57600622/214203225-236c3159-bfdd-48b0-81bf-8a4aa99081ed.png)

**Comment by Flipsoul** [comment]
i wont be able to verify or get pictures till the end of the week, but i believe my particular issue was between prints of
Nevermore_Micro/V5_Duo/Mods/Slide-in-Magnets_by-ChainsDDNevermore_Micro/V5_Duo/Mods/Slide-in-Magnets_by-ChainsDD/Duo_Plenum_wago.stl
And
Nevermore_Micro/V5_Duo/V2/V2_Duo_Plenum_LID.stl

There are a quite a few different solid model files/mesh files, so its possible i have a mismatch

**Comment by Flipsoul** [comment]
Looks like it was a mismatch. I'm seeing more files within the slide in magnet mod folder than i did before including the plenum lid file, which i want seeing before. (Couldn't see any of the images in the plenum lid file before too) Not sure why i want seeing them before.
