### ISSUE TITLE
nevermore V5_duo - Plenum lid make fans loud and weak!

### ISSUE THREAD

**Issue by Hrumque** [nevermore3d/Nevermore_Micro#29]
The project looks very nice optically, but in practice - I had my doubts when printing, and the first launch confirmed them.
Very nice cover over the fans - it has a very narrow airflow channel. It chokes the fans. After putting it on, you can immediately hear the fans go to high speed - it means that they spin the air in a circle, instead of pumping it through the filter.

The first mod - I cut out the entire inner part of the lid with a weight. The fans are exposed.
I measured the air flow - almost 50% better flow with such a cut cover. And almost 6dB quieter operation (at full 24v power supply)

Because my pliers-cut cover looked ugly - I printed a new one, as in the picture - already with holes cut out for the fans.
![obraz](https://user-images.githubusercontent.com/29131157/229383077-a6298a41-6304-4c55-bce5-d46ce0be93d2.png)
Success.
Quiet (well, maybe not super quiet, but quieter than the original) with higher airflow. As a result - you can set almost half the power supply - there is the same air flow and it is very quiet.

**Comment by thenickdude** [comment]
6dB is huge, could you share your STL? I'd love to try it too.

**Comment by thenickdude** [comment]
Makes sense, I'll try that too

**Comment by 0ndsk4** [comment]
Thanks for this. Changing the lid design shortly.

**Comment by bistory** [comment]
> 6dB is huge, could you share your STL? I'd love to try it too.

If you want, here is a quickly modded lid (I just cut 38mm holes into the existing lid)
[LID.stl.zip](https://github.com/nevermore3d/Nevermore_Micro/files/11524019/LID.stl.zip)

I'm printing it right now :-)

**Comment by 0ndsk4** [comment]
Thanks. Testing has shown the lid design wasn't optimal. This "bug" has now been squashed in the new Micro V6. When cad files are online its likely possible to use them to update the V5 lid for people who do not wish to upgrade their micros.
