### ISSUE TITLE
V5 Cartridge Lid CAD files

### ISSUE THREAD

**Issue by westminsterflip** [nevermore3d/Nevermore_Micro#3]
I did not see a cartridge lid in any of the cad files so I was hoping to get the f3d/step file for that if possible

**Comment by eduncan911** [comment]
I can confirm, it's missing the STEP for the Cartridge Lid.  I think we should clean up that root folder as most should be using V0/V1/V2/Mods folders.

If you are looking for the STLs to print, you can find two different sizes here: https://github.com/nevermore3d/Nevermore_Micro/tree/master/V5_Duo/V2

Sadly, I cannot install F360.  So I am unable to view the f3d files.

ping @0ndsk4

**Comment by 0ndsk4** [comment]
Added it to the root directory. Thanks.
