### ISSUE TITLE
STL files are missing?

### ISSUE THREAD

**Issue by kkingengineering** [nevermore3d/Nevermore_Micro#34]
Heads up - there are no STL/STEP files in the git for Micro V6. Did they not upload? Would like to start printing this asap. Thank you for your work.

**Comment by 0ndsk4** [comment]
Just making sure things will print as good for others too before uploading or instructing anything officially. Today I learned it good if the jalousie lid is heated upon first insertion, and made a few edits to lessen the chances of failure. You’re welcome to test the beta release files on Nevermore discord in the meantime: https://discord.gg/pgppCmjA
