### ISSUE TITLE
[V6] Unsupported overhang issue on plenum

### ISSUE THREAD

**Issue by max-cz** [nevermore3d/Nevermore_Micro#35]
Hi

Is this an errors or how is the printer going to print these? 
Layer 347.
Sliced with PIF standard in Orca and Superslicer.

![image](https://github.com/nevermore3d/Nevermore_Micro/assets/49396891/83b9f0b6-8886-4b1f-a7ca-4a0a803bed90)

**Comment by scheini79** [comment]
> Hi
> 
> Is this an errors or how is the printer going to print these? Layer 347. Sliced with PIF standard in Orca and Superslicer.
> 
> ![image](https://user-images.githubusercontent.com/49396891/243196295-83b9f0b6-8886-4b1f-a7ca-4a0a803bed90.png)

You need to turn it 90 degree. You’re printing it in the wrong direction.

**Comment by eambos** [comment]
This issue was reported on the Nevermore Discord. It's due to a 0.4 degree misalignment. 
![image](https://github.com/nevermore3d/Nevermore_Micro/assets/24357788/ba556b89-8cb9-43e4-85ce-5a33676bbae1)

**Comment by scheini79** [comment]
> This issue was reported on the Nevermore Discord. It's due to a 0.4 degree misalignment.
> ![image](https://user-images.githubusercontent.com/24357788/243199178-ba556b89-8cb9-43e4-85ce-5a33676bbae1.png)

But in his picture it’s clearly standing, not laying flat.

**Comment by 0ndsk4** [comment]
Thank you. As noted, somehow the bridge had a 0.4 degree angle causing it to be sliced in half. It’s been corrected in the cad file, and a new stl export will be up soon!
