### ISSUE TITLE
Built in supports fail

### ISSUE THREAD

**Issue by kkingengineering** [nevermore3d/Nevermore_Micro#37]
Printed in ASA using same settings as all other Voron parts I have made. These settings usually make clean results. Maybe an adjustment on this support so it anchors better on the left side? Maybe post a version with no built in supports so we can attempt via our own slicer? Thx.

![image](https://github.com/nevermore3d/Nevermore_Micro/assets/52836439/3501673d-87ec-40ce-82f6-d48b2b21fa2d)

**Comment by 0ndsk4** [comment]
Thanks. I’ve seen supports fail on both sides for some users. I’ll look into it and if all else fail export a file without the supports.
