### ISSUE TITLE
V6 STL files have unprintable fragments

### ISSUE THREAD

**Issue by Vykori** [nevermore3d/Nevermore_Micro#38]
The STL files for the Jalousie, and to a lesser extent also the Plenum and Cartridge, are detected as having lots of objects in 1 file. For instance in Super Slicer, the "Split to Objects" or "Split to Parts" functions will reveal all of the tiny pieces that are too small to print

![image](https://github.com/nevermore3d/Nevermore_Micro/assets/16940637/9c613b77-b69f-4dc3-bbca-e67bb9f3f87c)

**Comment by 0ndsk4** [comment]
Are there any images, the jalousie has a lot of small gaps everywhere to force the slicer to print the walls in a certain direction in every layer, so I would expect some slicers to object.
