### ISSUE TITLE
Plenum side mounting holes reversed for a v2.4.

### ISSUE THREAD

**Issue by uosdwishpoom** [nevermore3d/Nevermore_Micro#41]
Mounting holes on the plenum sides do not line up in the middle of the 2020 rails on the bottom of a v2.4.  They are offset 2 to 3 mm causing misalignment with the 90 degree filtration medium box.  The filtration box fits snug but fine to the bottom panel on a v2.4 with whoppingpochard kinematic mounts which doesn't leave room to tilt the filtration medium box to the offset plenum.

**Comment by 0ndsk4** [comment]
Thank you. Don’t know what has happened. Fixing it now.

**Comment by uosdwishpoom** [comment]
Thanks for the great work that you do for our health and well being.  Your
designs are outstanding. Looking forward to making a stealthmax when it is
released.
