### ISSUE TITLE
Routing wires in V6?

### ISSUE THREAD

**Issue by VitalyBrusentsev** [nevermore3d/Nevermore_Micro#44]
Hi, 
Could the V6 documentation be extended to include the wire routing instructions? With full size fans, it is not clear where the wires should go from the fans to the compartment. I tried to do this just snuggly on top, but it seems to not match the design intention, as it leads to the lid bulging in the middle:
![image](https://github.com/nevermore3d/Nevermore_Micro/assets/9266101/65788a2a-343e-43c3-883b-06727629d5b6)

**Comment by 0ndsk4** [comment]
The center wire space created by the cutout in the lid is 1.8mm in depth, afaik more than the thickness of any 5015 type wire. Increasing the depth is possible, but would increase risk of vibration movement of fan and wires and possible premature failure.

If wires lie flat, there shouldn't be any bulge in the lid. If you get a bulge, make sure that you have removed all support material on the bottom inside of the compartment, and that the wires lie flat and non-overlapping.
I added motion-GIFs to the main v6 page for full clarity.

![wire_space](https://github.com/nevermore3d/Nevermore_Micro/assets/63494590/7692cf2d-29f6-4a13-a96d-0cade764abd5)
