### ISSUE TITLE
Missing fan hole supports in GDStime v0 model

### ISSUE THREAD

**Issue by Haxk20** [nevermore3d/Nevermore_Micro#45]
In commit https://github.com/nevermore3d/Nevermore_Micro/commit/833f6378ff79b707f6215a9e0d42d92e39b9bcc6 the fan hole supports were removed causing significant drooping of plastic on the overhangs in that area.

The other model still kept the supports so Im pretty sure this is an unwanted change and was left out by accident.

**Comment by 0ndsk4** [comment]
Was fixed the same day, thx!
