### ISSUE TITLE
Its not made clear how long the carbon that is resold lasts

### ISSUE THREAD

**Issue by hYdos** [nevermore3d/Nevermore_Micro#61]

**Comment by 0ndsk4** [comment]
Hi!

The original manufacturer guarantees two years. Worst case, it’s six months old by the time it gets to vendors. Most vendors restock with 1-3 months interval, but say a worst case here would be six months as well, it’s still perfectly good for use a year after purchase (and likely longer as it’s quite optimally stored in a light vacuum compression with very few factors that can deplete or damage the micro-porosity). 

But you can assume Nevermore carbon is good for at least a year, and likely longer.

**Comment by hYdos** [comment]
thanks for the info
