### ISSUE TITLE
how to protect carbon if not printing around the clock?

### ISSUE THREAD

**Issue by bubnikv** [nevermore3d/Nevermore_Micro#8]
Hello.

Reading the instructions at your distributor
https://lecktor.com/en/v2x-misc/870-nevermore-carbon.html
and other sources I got that carbon will be depleted if exposed to the air.

Now if I do not print regularly and I want to use the product referenced above for more than 6 months, what is the recommended procedure? 

What is the shelf life of the vacuumed carbon?

What is the shelf life of the bag if the vacuumed bag was opened and then sealed just with the bag seal?

Would you please consider selling smaller vacuumed packages so that if one does not print ABS regularly, one can keep the carbon fresh longer?

Does it make sense to remove the whole filter assembly filled with fresh carbon from the printer and seal it into a sealed bag between prints to keep the carbon fresh? This is something I would consider as a good nature friendly practice.

Thanks for a great product.

**Comment by 0ndsk4** [comment]
Hi, sorry for being inattentive!

* Shelf life is about 2 years for activated carbon, even when stored air tight (it will work after that too, just not as great). 
* If stored in an air tight container (ie a good bag seal), shelf life is almost the same. The carbon will only be exposed to VOCs whenever you break the seal, a for a few short seconds/minutes. 
* If there’s demand for it, sure. But the bag is pretty small already, and two years to use it so… also, with the exception of possibly natural PLA and PETG in a well ventilated space, it’s a good idea to use the carbon for other filaments as well. 

* removing the cartridge and putting it in a sealed plastic bag between prints would increase filtration duration, possibly by quite a lot. But personally, I’d just forget. Lucky we’re all different :)
