### ISSUE TITLE
BOM error - Magnets are '3x6' not '6x3'

### ISSUE THREAD

**Issue by RudyAlbertoAcostaMarmalade** [nevermore3d/Nevermore_Micro#9]
As the title states - I now have to find some creative use for some very long and thin cylindrical magnets :D

Thank you for taking the time to develop the Nevermore!

**Comment by wkeifenheim** [comment]
I nearly made the same mistake, but when I couldn't find 3x6 magnets on Amazon I read closer and saw in the v5 changes section states `BOM 3x6 magnets are standard`. Standard BOM is 6x3 so I then compared the v5 plenum to other Voron V2 parts and confirmed that the BOM listing should state 6x3.
![image](https://user-images.githubusercontent.com/639361/163752887-d5a66d1b-e774-4328-be63-5e5fbd7bbe97.png)

**Comment by wkeifenheim** [comment]
Someone has already submitted a PR to fix this: https://github.com/nevermore3d/Nevermore_Micro/pull/5

**Comment by 0ndsk4** [comment]
Thanks, is corrected in the V5 BOM section now!
